os: linux
language: android
licenses:

android:
  components:
  
jdk: oraclejdk8
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
language: node_js
before_script:
  - npm install -g flutter-cli
script:  
  - flutter build apk -t lib/main_prod.dart

cache:
  directories:
    - $HOME/.pub-cache