
os: linux
language: android
android:
  components:
     - tools
     - platform-tools
     - tools
     - build-tools-27.0.3
     - android-27
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'  
jdk: oraclejdk8
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
env:
  - NODE_VERSION="8"
before_install:
  # Installing Node.js
  - nvm install $NODE_VERSION
install:
  - echo y | sdkmanager 'ndk-bundle'
  - echo y | sdkmanager 'cmake;3.6.3155560'
  - export ANDROID_HOME=$HOME/android/sdk
  - export ANDROID_NDK_HOME=$HOME/android/sdk/ndk-bundle
before_script:
  - npm install -g flutter-cli
script:  
  - cd device_calendar/example
  - flutter build apk
cache:
  directories:
    - $HOME/.pub-cache