os: linux
language: android
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
android:
  components:
     - tools
     - platform-tools
     - build-tools-27.0.3
     - android-27
  
jdk: oraclejdk8
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
language: node_js
before_script:
  - npm install -g flutter-cli
script:  
  - cd device_calendar/example
  - flutter build apk

cache:
  directories:
    - $HOME/.pub-cache