name: dual_screen
description: A new flutter plugin project.
version: 0.0.1-dev
homepage: https://github.com/builttoroam/flutter_plugins/tree/master/dual_screen

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.builttoroam.dual_screen
        pluginClass: DualScreenPlugin
