name: device_calendar
description: A cross platform plugin for displaying local notifications.
version: 0.0.1
author: Built to Roam
homepage:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.builttoroam.devicecalendar
    pluginClass: DeviceCalendarPlugin
