name: device_calendar
description: A cross platform plugin for modifying calendars on the user's device.
version: 1.0.0+3
author: Built to Roam <info@builttoroam.com>
homepage: https://github.com/builttoroam/flutter_plugins/tree/master/device_calendar

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.builttoroam.devicecalendar
    pluginClass: DeviceCalendarPlugin

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"